// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KPTOK1O8jvcdHy73oZfXerThEFFm6Sw',
    appId: '1:821834349796:web:af1257804dbf8b3772c0f1',
    messagingSenderId: '821834349796',
    projectId: 'teste-8ad40',
    authDomain: 'teste-8ad40.firebaseapp.com',
    databaseURL: 'https://teste-8ad40.firebaseio.com',
    storageBucket: 'teste-8ad40.appspot.com',
    measurementId: 'G-GJWXDFLEX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-dU4qG0wTc6jS2zpPx2MxLVr83Rz2TQ',
    appId: '1:821834349796:android:d1e9222c75caed9772c0f1',
    messagingSenderId: '821834349796',
    projectId: 'teste-8ad40',
    databaseURL: 'https://teste-8ad40.firebaseio.com',
    storageBucket: 'teste-8ad40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3_osQciLUu-pQqN1jXfE90HPg7CVwnQ',
    appId: '1:821834349796:ios:c3188dd620d0136b72c0f1',
    messagingSenderId: '821834349796',
    projectId: 'teste-8ad40',
    databaseURL: 'https://teste-8ad40.firebaseio.com',
    storageBucket: 'teste-8ad40.appspot.com',
    iosClientId: '821834349796-9cqg9q1l4qk4a2i24rcalv8ra766qk38.apps.googleusercontent.com',
    iosBundleId: 'com.example.onofffire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3_osQciLUu-pQqN1jXfE90HPg7CVwnQ',
    appId: '1:821834349796:ios:c3188dd620d0136b72c0f1',
    messagingSenderId: '821834349796',
    projectId: 'teste-8ad40',
    databaseURL: 'https://teste-8ad40.firebaseio.com',
    storageBucket: 'teste-8ad40.appspot.com',
    iosClientId: '821834349796-9cqg9q1l4qk4a2i24rcalv8ra766qk38.apps.googleusercontent.com',
    iosBundleId: 'com.example.onofffire',
  );
}
